apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: w3291h88x-go 
  janus-idp.io/tekton: w3291h88x-go
  backstage.io/kubernetes-id: w3291h88x-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: w3291h88x-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml