apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: w3291h88x-go-gitops
  description: This is GitOps manifest for w3291h88x-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=w3291h88x-go
    backstage.io/kubernetes-id: w3291h88x-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: w3291h88x-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:w3291h88x-go
